Guest search hotel
BSPQ18-19/BSPQ19-E2 pull request #23
Opened 2019-04-23 13:41 UTC by Arribas12

Being a guest user you can search for the available hotels from a selected date. You can also logout.
There are some javadocs on IHotelDao.
HotelDaoTest missing

2019-04-24 11:38 UTC, iapellaniz requested changes
- Functionality looks good, although the UI is not that intuitive to use (we can sort it out in another PR)
- Merge master into the branch to see if it works and implement new changes
- Missing tests
- Lots of uncommented code

2019-04-24 11:49 UTC, iapellaniz reviewed
- Please use `LocaleManager` for displaying UI messages.

- I see you're using your own UI system instead of views. This will be problematic.
 The problem is that if you use only one `View` and inside that view you show different "Screens" with different purposes and permission levels, the system won't know how to handle a permission level change (log in, log out, ...). If you decide to keep the current system (instead of using different views for each window), you'll have to properly implement the `getViewPermission` and `getViewType` so that the correct `ViewType` and `ViewPermission` gets returned.
    - Also, please keep in mind that if the `ViewManager` needs to open another window your UI system must be able to be instantiated multiple times with different screens active.

2019-04-24 11:49 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/HotelGuestSearchingPanel.java
> +					JOptionPane.showMessageDialog(null, "Please select a date", "Error", JOptionPane.ERROR_MESSAGE);
Use `LocaleManager` when displaying text in the client UI

2019-04-24 11:49 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/HotelGuestSearchingPanel.java
> +						JOptionPane.showMessageDialog(null, "There are no hotels available", "Error", JOptionPane.ERROR_MESSAGE);
Use `LocaleManager` when displaying text in the client UI

2019-04-24 11:49 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/HotelGuestSearchingPanel.java
> +		confirm = new JButton("Confirm");
Use `LocaleManager` when displaying text in the client UI

2019-04-24 11:49 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/HotelGuestSearchingPanel.java
> +					JOptionPane.showMessageDialog(null,  "Successfully logged out", "Logged out",JOptionPane.INFORMATION_MESSAGE);
Use `LocaleManager` when displaying text in the client UI

2019-04-24 11:49 UTC, iapellaniz commented on src/main/java/es/deusto/spq/server/data/jdo/Hotel.java
> +	private ArrayList<Room> room;
Try to use `List` instead of `ArrayList`

2019-04-24 15:33 UTC, iker-barriocanal requested changes
There's a lot of documentation missing.

2019-04-25 09:46 UTC, iapellaniz commented on src/main/java/es/deusto/spq/server/data/dao/HotelDAO.java
> +//			if (pm != null && !pm.isClosed()) {
Please, if the code isn't used, remove it instead of commenting it out

2019-04-28 20:19 UTC, Egoes98 commented
First you shold merge master into this branch to resolve all the conflict and see if it works together.

-Test Fails
![image](https://user-images.githubusercontent.com/31927438/56869466-862b3180-6a01-11e9-8d62-02530260adae.png)
-It work fine but some changes should be made. When you signIn as a guest it should show only the Guest GUI if you log in as an admin only the admin one.
-More documentation(Look at the checklist to see what documentation you are missing):

2019-04-28 20:27 UTC, Egoes98 submitted a review, later dismissed
-Test fails
![image](https://user-images.githubusercontent.com/31927438/56869733-81b44800-6a04-11e9-9df9-f0da62390988.png)
-When you log in as guest you shold only see guest window and when admin only the admin. seen the execution i suposse is not like that.
-More documentation(look at the ckecklist report to see the requested javadock)

2019-04-28 20:27 UTC, Egoes98 commented on src/main/java/es/deusto/spq/server/data/jdo/Room.java
> +//	private List<String> features;
Remove unused code

2019-04-29 06:33 UTC, Arribas12 commented on src/main/java/es/deusto/spq/server/data/jdo/Room.java
> +//	private List<String> features;
check now if it is corrected please

2019-04-29 16:27 UTC, iapellaniz submitted a review, later dismissed
Looking good!

Just a couple of simple changes:

- Please, remove the "Log out" buttons and dialogs, as that will now be handled by the new User system.
- When I select a row from the results table, it turns red. Is it intentional?
- Please use the Locale system! If you have doubts about it, look at #26 to see an example implementation

Thanks! If you need help about the last one just tell me

2019-04-29 18:40 UTC, Egoes98 approved these changes
I think its good.

2019-04-29 19:07 UTC, iker-barriocanal approved these changes
Try to improve your code (e.g. using `List` instead of `ArrayList` in the method's definition); and the more documentation you do the better. All in all, good.

2019-04-29 21:05 UTC, merged