Register admin
BSPQ18-19/BSPQ19-E2 pull request #39
Opened 2019-04-30 13:34 UTC by Egoes98

Added register admin window on the admin panel. Also avery time you run the server it creates a default admin because you need an admin to cerate more.

2019-05-03 09:37 UTC, iapellaniz reviewed
We should remove phone, as it's not stored for Administrators

2019-05-03 09:55 UTC, Egoes98 commented
> We should remove phone, as it's not stored for Administrators

Its alredy changed.

2019-05-03 10:14 UTC, iapellaniz requested changes

2019-05-03 10:14 UTC, iapellaniz commented on src/main/java/es/deusto/spq/server/remote/IHotelManager.java
> +	 * @param phone
Remove phone mentions from code

2019-05-03 10:14 UTC, iapellaniz commented on src/main/resources/localization_en_US.properties
> +register.admin.label.phone = Phone number:
Remove phone mentions from code

2019-05-03 10:14 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/base/ViewFactory.java
> +            case REGISTER_ADMINISTRATOR:
New line before `case` please

2019-05-04 10:34 UTC, iapellaniz approved these changes

2019-05-04 10:36 UTC, merged