Payment view
BSPQ18-19/BSPQ19-E2 pull request #51
Opened 2019-05-19 13:59 UTC by Egoes98

This class has the methods and the view for reservation. This lets you choose how to pay and insert payment data. This view is called once you clicked the confirm button to make a reservation. As iker did it, it conects to the paypal or mastercard servers and there the payment is handled. If payment is accepted the reservation is done.

2019-05-19 19:09 UTC, iker-barriocanal requested changes
Please, document code writing a brief description of what methods do, not just the description of arguments.

2019-05-20 06:45 UTC, iapellaniz reviewed
What data can I use for payment?

2019-05-20 06:45 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/views/guest/UserPayView.java
> +		frame.setVisible(true);
Missing call to the `addDisposeEventHandler` method here.

2019-05-20 06:45 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/views/guest/UserPayView.java
> +		 *
Empty comment

2019-05-21 12:07 UTC, Egoes98 commented
I have added a txt in the last commit with the accounts that can be use for paying, also you can see them in this comment.
PayPal accounts

| Username  | Password |
| ------------- | ------------- |
| iker-barriocanal  | 123  |
| iapellaniz  | deusto  |
| Egoes98 | 7954 |
| Arribas12 | arribas12 |
| dusekvojtech | deusto2019 |

MasterCard accounts

| CardNumber | SecretCode |
| -------------- | ------------- |
|123456789|123|
|465789123|456|
|789123456|789|

2019-05-22 14:02 UTC, iker-barriocanal approved these changes
Good!

2019-05-22 14:17 UTC, merged