Cancel reservation
BSPQ18-19/BSPQ19-E2 pull request #58
Opened 2019-05-22 20:57 UTC by Arribas12

When you click a reservation and then you click the button cancel reservation it is deleted from the database

2019-05-22 21:29 UTC, iapellaniz requested changes

2019-05-22 21:29 UTC, iapellaniz commented on src/main/java/es/deusto/spq/client/gui/views/reservations/ReservationDetailView.java
> +        		getViewManager().getClient().getController().deleteReservation(reservationDTO.getId());
The window should be closed after cancelling

2019-05-22 21:29 UTC, iapellaniz commented on src/main/java/es/deusto/spq/server/remote/HotelManager.java
> +		if(state == true) {
`return state` will do the same thing

2019-05-22 21:29 UTC, iapellaniz commented on src/main/resources/localization_es_ES.properties
> +  Íñigo Apellániz (iapellaniz@opendeusto.es)<br>\
:'(

2019-05-23 08:17 UTC, Egoes98 requested changes
Only one of the windoes is closed, could yo close the twoo of them?? I mean that it closes the one where you see the info and the other  keep open so you still see the information until you close the View my reservations and open it again.

2019-05-23 08:24 UTC, Egoes98 commented
> Only one of the windoes is closed, could yo close the twoo of them?? I mean that it closes the one where you see the info and the other keep open so you still see the information until you close the View my reservations and open it again.

I am doing it myself, I have nearly finished.

2019-05-23 08:28 UTC, Egoes98 commented
> > Only one of the windoes is closed, could yo close the twoo of them?? I mean that it closes the one where you see the info and the other keep open so you still see the information until you close the View my reservations and open it again.
> 
> I am doing it myself, I have nearly finisheI have tried doing a setter but is trykier than i thougt. I dont know if I would be able. Look at how to do it please.

2019-05-23 08:31 UTC, Egoes98 commented
Okay I have done it. Now both are closing.

2019-05-23 08:33 UTC, iapellaniz approved these changes

2019-05-23 08:34 UTC, Egoes98 approved these changes

2019-05-23 08:44 UTC, merged